[project]
name = "061025-cw"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi==0.118.0",
    "pip==25.2",
    "pydantic==2.11.10",
    "uv==0.8.23",
    "uvicorn[standard]>=0.37.0",
]
